version: "3"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "member"
      MYSQL_USER: "member"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Europe/Stockholm"
    ports:
      - 3306:3306
    expose:
      - 3306
