version: "3.8"

services:
  app:
    image: tullingedk/member:latest
    restart: always
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_HOSTED_DOMAIN: "${GOOGLE_HOSTED_DOMAIN}"
      SECRET_KEY: "${SECRET_KEY}"
      OAUTHLIB_INSECURE_TRANSPORT: "${OAUTHLIB_INSECURE_TRANSPORT}"
      TZ: "Europe/Stockholm"
      PORT: "${PORT}"
      SECRET_KEY: "${SECRET_KEY}""
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
