version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    image: tullingedk/member:latest
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GOOGLE_HOSTED_DOMAIN: '${GOOGLE_HOSTED_DOMAIN}'
      SECRET_KEY: '${SECRET_KEY}'
    depends_on:
      - mysql
      - redis
    ports:
      - 5000:5000
    expose:
      - 5000
